### ISSUE TITLE
Flatpak builder doesn't detect when a python script crash

### ISSUE THREAD

**Issue by bilelmoussaoui** [flatpak/flatpak-builder#209]
I have been working on updating Lollypop to the latest version on Flathub. The build stops and I was getting this issue. 
```
Process ForkPoolWorker-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 343, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/synchronize.py", line 99, in __exit__
    return self._semlock.__exit__(*args)
ValueError: semaphore or lock released too many times
```
But the builder doesn't detect that build is stopped. 
See this for more info https://flathub.org/builds/#/builders/24/builds/375

**Comment by barthalion** [comment]
I think we've seen this before, but I can't remember the details. @alexlarsson any idea?

**Comment by alexlarsson** [comment]
Yes, i remember seeing something like this, but I don't think we ever figured out what was causing it.

**Comment by alexlarsson** [comment]
Its some kind of deadlock i think. I believe we worked around it by disabling the parallel building for some module, or something like that?

**Comment by alexlarsson** [comment]
Ideally we should figure out why it goes all wrong though.

**Comment by nanonyme** [comment]
That crashing process is not main anyhow. If you just listen on main which never finishes because its child died, you would probably get stuck

**Comment by nanonyme** [comment]
multiprocessing is kinda awful because it involves threading in main so there's two different levels of concurrency that can break. I suspect root cause is a Python bug
