### ISSUE TITLE
Temporary failure in name resolution when building a Meson project with a wrap

### ISSUE THREAD

**Issue by rockfireredmoon** [flatpak/flatpak-builder#287]
## Linux distribution and version

Linux Mint 19.1 Tessa (also tested on Ubuntu 19.04 and Fedora 30)

## Flatpak-builder version

flatpak-builder 0.10.9

## Description of the problem

flatpak-builder is failing with a Meson based module (using a git source) with the following error when it reaches the stage where meson downloads it's dependencies from [WrapDB](https://mesonbuild.com/Wrap-dependency-system-manual.html), in this case zlib.  

```
The Meson build system
Version: 0.50.1
Source dir: /run/build/player
Build dir: /run/build/player/_flatpak_build
Build type: native build
Project name: sparkplayer
Project version: 0.9.9
Appending LDFLAGS from environment: '-L/app/lib '
Native C compiler: ccache cc (gcc 8.3.0 "cc (GCC) 8.3.0")
Appending LDFLAGS from environment: '-L/app/lib '
Native C++ compiler: ccache c++ (gcc 8.3.0 "c++ (GCC) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring BuildConfig.h using configuration
Downloading zlib source from http://zlib.net/fossils/zlib-1.2.11.tar.gz
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 122, in run
    return options.run_func(options)
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 246, in run
    app.generate()
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 163, in generate
    self._generate(env)
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 193, in _generate
    intr.run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3817, in run
    super().run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 438, in evaluate_statement
    return self.assignment(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 1019, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2365, in func_subproject
    return self.do_subproject(dirname, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2404, in do_subproject
    resolved = r.resolve(dirname)
  File "/usr/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 144, in resolve
    self.get_file()
  File "/usr/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 208, in get_file
    path = self.get_file_internal('source')
  File "/usr/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 326, in get_file_internal
    self.download(what, cache_path)
  File "/usr/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 308, in download
    dhash, tmpfile = self.get_data(srcurl)
  File "/usr/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 258, in get_data
    resp = urllib.request.urlopen(url, timeout=req_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
Error: module player: Child process exited with code 2

```

My manifest looks like this :-

```
{
	"app-id": "org.icemoon.Player",
	"runtime": "org.freedesktop.Platform",
	"runtime-version": "18.08",
	"sdk": "org.freedesktop.Sdk",
	"command": "player",
	"finish-args": [
		"--share=network",
		"--device=dri",
		"--socket=pulseaudio",
		"--socket=x11",
		"--share=ipc"
	],
	"modules": [
		{
			"name": "player",
			"buildsystem": "meson",
			"config-opts": [
				"-Dgtk=false"
			],
			"sources": [
				{
					"type": "git",
					"path": "../player"
				}
			],
			"modules": [
				"boost.json"
			]
		}
	]
}
```

The only external dependency that is currently needed is boost. This downloads and compile fine before getting to the application, which uses WrapDB for 3 dependencies (and so will require to download them), and everything else is included in the source tree.

I have tried using ..

```
flatpak-builder --run app org.icemoon.Player.json sh
```

.. to get a shell and have a poke about.  It appears to only happen when running flatpak-builder.

```
sh-4.4$ python3
Python 3.7.3 (default, Nov 10 2011, 15:00:00) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> print("Address:" + socket.gethostbyname('zlib.net'))
Address:68.66.224.164

```

At first I suspected something to do with how resolv.conf is handled, but it looks to me like it should work.

I can see a mount to /etc/resolv.conf

```
sh-4.4$ df|grep resolv
tmpfs             1637236       3528   1633708   1% /etc/resolv.conf
```

And the contents look like ..

```
sh-4.4$ cat /etc/resolv.conf 
# Generated by NetworkManager
search mydomain.local
nameserver 192.168.91.1
```

That nameserver address is my router, but after coming across some bug reports for flatpak itself that looked kinda related I tried various different methods of name resolution as well. This includes using dnsmasq, systemd-resolved and configuring all totally manually, the results were always the same.

I should also say that I do not use a proxy server.

## Steps to reproduce

1. Create a meson project that uses a wrap such as zlib. 
2. Create a manifest to package this project.
3. Run flatpak-builder

**Comment by rockfireredmoon** [comment]
Oopps. Sorry, I'll close this. After trawling through some other bug reports I came across this - https://github.com/flatpak/flatpak-builder/issues/211 - which pointed me to 'build-options' with --share=network. 

I hadn't realised the build itself runs in a sandbox by the default. The presence of the --sandbox option kind of suggested to me that by default it doesn't.

**Comment by refi64** [comment]
Just as an FYI, flathub probably won't accept a build that needs network, try using `--wrap-mode=nodownload` with Meson.

**Comment by rockfireredmoon** [comment]
Oh thanks. I'll give that a try. Although for various reasons this particular project I do not intend to publish on Flathub, but noted :)
